disabled_rules:
- line_length
opt_in_rules:
- array_init
- closure_end_indentation
- closure_spacing
- contains_over_first_not_nil
- empty_count
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- let_var_whitespace
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- object_literal
- operator_usage_whitespace
- overridden_super_call
- pattern_matching_keywords
- private_outlet
- prohibited_super_call
- redundant_nil_coalescing
- trailing_closure
- unneeded_parentheses_in_closure_argument
- vertical_parameter_alignment_on_call
- vertical_whitespace
- untyped_error_in_catch
- unavailable_function
- modifier_order
- multiline_arguments
- multiline_function_chains
- empty_string
- discouraged_optional_boolean
- anyobject_protocol
- function_default_parameter_at_end
- private_action
- sorted_first_last
cyclomatic_complexity:
  ignores_case_statements: true
